networks:
  default:
    external: true
    name: docker-bridge
volumes:
  mariadb-invoice-data:
  node_modules:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: invoice-api
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=5000
      - API_KEY=${API_KEY}
      - DB_HOST=mariadb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - mariadb

  mariadb:
    image: jc21/mariadb-aria:latest
    container_name: mariadb
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_AUTO_UPGRADE="1"
      - TZ='Asia/Jakarta'
    volumes:
      - mariadb-invoice-data:/var/lib/mysql
      - ./src/db/database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql
      - ./docker/mariadb/conf.d/my.cnf:/etc/my.cnf.d/my.cnf:ro
    ports:
      - 3306:3306
