networks:
  default:
    external: true
    name: docker-bridge
volumes:
  mariadb-data:
  node_modules:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    image: ghcr.io/danne56/invoice-bot-api:latest
    container_name: invoice-api
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=5000
      - API_KEY=${API_KEY}
      - DB_HOST=mariadb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - 5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mariadb:11.8.3
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_AUTO_UPGRADE="1"
      - TZ='Asia/Jakarta'
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./src/db/database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql
      - ./docker/mariadb/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - 3306
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
